# Generated by Django 4.1.3 on 2022-11-20 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('espanol', 'Espanol'), ('english', 'English')], max_length=50)),
                ('course_length', models.CharField(default=0, max_length=20)),
                ('payment', models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='paid', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=18, max_digits=18, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
