import Head from 'next/head'
import { useAuth } from '@/hooks/auth'
import CardCourse from '@/components/card/cardCourse'
import styles from '@/styles/course.module.css'
export default function Home() {

  const { user} = useAuth()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
          {user ? (
                  <a >no login</a>
              ) : (
                <>
                    <a >login</a>
                </>
              )}
        </div>
      <CardCourse title={'Cursos'} />
    </>
  )
}
